name: convert-c—à
on: 
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Download flake8
        run: |
            python -m pip install --upgrade pip
            pip install flake8

      - name: Run linter
        run: flake8 .
        
